---
apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: famous-quotes
      name: famous-quotes
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: famous-quotes
      template:
        metadata:
          labels:
            app: famous-quotes
        spec:
          containers:
            - name: famous-quotes
              image: quay.io/redhattraining/famous-quotes:2.1
              ports:
                - containerPort: 8000
                  protocol: TCP
              env:
                - name: QUOTES_HOSTNAME
                  value: <CHANGE_ME>
                - name: QUOTES_USER
                  value: admin
                - name: QUOTES_DATABASE
                  value: quotesdb
                - name: QUOTES_PASSWORD
                  value: redhat123
              securityContext:
                capabilities:
                  drop:
                    - ALL
                allowPrivilegeEscalation: false
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: famous-quotes
      name: famous-quotes
    spec:
      ports:
        - protocol: TCP
          port: 8000
          targetPort: 8000
      selector:
        app: famous-quotes
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: famous-quotes
      name: famous-quotes
    spec:
      port:
        targetPort: 8000
      to:
        kind: Service
        name: famous-quotes
      tls:
        termination: edge
