---
serviceAccount:
  create: true
  name: grafana-sa
  annotations:
    eks.amazonaws.com/role-arn:
      <CHANGE_ME>
securityContext:
  runAsUser: null
  runAsGroup: null
  fsGroup: null
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

grafana.ini:
  auth:
    sigv4_auth_enabled: true

adminUser: admin
adminPassword: redhat123
