---
apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: openshift-cert-manager-operator-group
      namespace: ack-system
    spec:
      upgradeStrategy: Default
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: ack-sqs-controller
      namespace: ack-system
    spec:
      channel: alpha
      installPlanApproval: Automatic
      name: ack-sqs-controller
      source: community-operators
      sourceNamespace: openshift-marketplace
